### PR TITLE
update playslinine videojs

### PR DESCRIPTION
**Pull request by tomjohnson916**

### CODE REVIEW

**Comment by ptvandi** [comment]
@tomjohnson916 Thanks for creating the PromtheanTV fiddle account. Do we want to update all the fiddle links in here?

**Comment by ptvandi** [comment]
Sorry closed on accident

**Comment by tomjohnson916** [comment]
@ptvandi - updated formatting across several examples as requested. working on updating jsfiddle links now.

**Comment by ptvandi** [comment]
@tomjohnson916 Rad, thanks! Just let me know when it's done and we can merge.

**Pull request merged**
